### ISSUE TITLE
jetson orin build failure

### ISSUE THREAD

**Issue by malv-c** [saharNooby/rwkv.cpp#108]
% cmake . -DRWKV_CUBLAS=ON
-- GGML CUDA sources found, configuring CUDA architecture
-- Configuring done (2.4s)
CMake Error at CMakeLists.txt:250 (add_library):
  Cannot find source file:

    /tmp/rwkv.cpp/ggml/src/ggml.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:250 (add_library):
  No SOURCES given to target: ggml

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by LoganDark** [comment]
clone the repository recursively
