### ISSUE TITLE
SyntaxError: invalid syntax on MacOS

### ISSUE THREAD

**Issue by realcarlos** [saharNooby/rwkv.cpp#109]
python rwkv/convert_pytorch_to_ggml.py RWKV-4-Raven-1B5-v12-Eng98%-Other2%-20230520-ctx4096.pth rwkv1B5.bin BF16
  File "rwkv/convert_pytorch_to_ggml.py", line 18
    def get_layer_count(state_dict: Dict[str, torch.Tensor]) -> int:
                                  ^
SyntaxError: invalid syntax

**Comment by saharNooby** [comment]
What's your Python version?

**Comment by realcarlos** [comment]
Python 3.10.9

**Comment by realcarlos** [comment]
python3 rwkv/chat_with_bot.py rwkv-169m-ggml-f16-new.bin. it woks, thank you.
