### ISSUE TITLE
it seems does not support the newly RWKV-4-World-CHNtuned-3B-v1-20230625-ctx4096.bin

### ISSUE THREAD

**Issue by lixianmin** [saharNooby/rwkv.cpp#124]
I can reproduce the process with RWKV-4-Raven-3B-v12-Eng49%-Chn49%-Jpn1%-Other1%-20230527-ctx4096.pt, but when I use the newly RWKV-4-World-CHNtuned-3B-v1-20230625-ctx4096.bin, it can not work properly, the command line only returns with messy codes

**Comment by saharNooby** [comment]
Hi! Please see if [this solution helps](https://github.com/saharNooby/rwkv.cpp/issues/123#issuecomment-1666729923).

**Comment by lixianmin** [comment]
> Hi! Please see if [this solution helps](https://github.com/saharNooby/rwkv.cpp/issues/123#issuecomment-1666729923).

thank you very for your reply. yes, it works.
