### ISSUE TITLE
Support build with cublas and hipblas on github action

### ISSUE THREAD

**Issue by Cyberhan123** [saharNooby/rwkv.cpp#151]

**Comment by saharNooby** [comment]
Can be copy-pasted from `llama.cpp`, since they already provide prebuilt cuBLAS DLLs in releases.

**Comment by Cyberhan123** [comment]
That's it, I'll try it

**Comment by Cyberhan123** [comment]
Right now https://github.com/Jimver/cuda-toolkit and https://github.com/Cyberhan123/rocm-toolkit is ready .
I think We are close to success
