### ISSUE TITLE
The linked Huging Face page in the README doesn't have any .bin files

### ISSUE THREAD

**Issue by krikru** [saharNooby/rwkv.cpp#159]
Under "Option 3.1. Download pre-quantized Raven model" in `README.md`, the instructions tell you to "check that you are downloading `.bin` file, not `.pth`," but on the [linked page](https://huggingface.co/BlinkDL/rwkv-4-raven/tree/main), there are `.pth` files but no `.bin` files.

**Comment by saharNooby** [comment]
Blink does not provide pre-quantized models for `rwkv.cpp` anymore, so I've removed the section.

I'm not comfortable officially recommending third-party pre-quantized models on Hugging Face, and instead recommend to do the conversion yourself.

However, [looks like latestissue on Hugging Face has uploaded all RWKV models in all available formats](https://huggingface.co/latestissue) -- you may find these useful, but use them at your own risk.
