### ISSUE TITLE
Mac Build stops with Errors

### ISSUE THREAD

**Issue by BuilderGuy1** [saharNooby/rwkv.cpp#29]
Just tried running cmake the latest release (master-0a8157d) and I get this error:

-- CMAKE_SYSTEM_PROCESSOR: arm64
-- ARM detected
CMake Error at CMakeLists.txt:229 (add_subdirectory):
  The source directory
    /Users/jhogue/Desktop/_Notes/ML_Local/rwkv.cpp/ggml

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:232 (set_target_properties):
  set_target_properties Can not find target to add properties to: ggml

-- Configuring incomplete, errors occurred!

**Comment by saharNooby** [comment]
Probably, you forgot to clone the submodules. Try deleting the repo and cloning it again using `git clone --recursive https://github.com/saharNooby/rwkv.cpp.git`

**Comment by BuilderGuy1** [comment]
Not an issue.

**Comment by LoganDark** [comment]
> Try deleting the repo and cloning it again

or running `git submodule update`
