### ISSUE TITLE
chat_with_bot will stop when '\n' in response.

### ISSUE THREAD

**Issue by wuyudi** [saharNooby/rwkv.cpp#36]
https://github.com/saharNooby/rwkv.cpp/blob/1be9fda24874f87d7e604b76f76359b1bb20cb2b/rwkv/chat_with_bot.py#L84-L86

then if the bot returns a '\n', `break`, it will be stopped.

**Comment by saharNooby** [comment]
The script was just changed in [the recent commit](https://github.com/saharNooby/rwkv.cpp/commit/ac663631e1132891f09375e0da89e2d99c276273), and this specific check was removed.
