### ISSUE TITLE
ggml_new_tensor_impl: not enough space in the context's memory pool

### ISSUE THREAD

**Issue by HCBlackFox** [saharNooby/rwkv.cpp#4]
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 4625438848, available 4538236928)
Traceback (most recent call last):
  File "D:\AI\rwkv.cpp\rwkv\chat_with_bot.py", line 4, in <module>
    model = rwkv_cpp_model.RWKVModel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\rwkv.cpp\rwkv\rwkv_cpp_model.py", line 37, in __init__
    self.ctx = self.library.rwkv_init_from_file(model_path, thread_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\rwkv.cpp\rwkv\rwkv_cpp_shared_library.py", line 74, in rwkv_init_from_file
    ptr = self.library.rwkv_init_from_file(model_file_path.encode('utf-8'), ctypes.c_uint32(thread_count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000008

Anyone know how to fix it?

**Comment by saharNooby** [comment]
>not enough space in the context's memory pool

Looks like there is a mistake in memory requirements table:
```
        static const size_t memory_required_mb[6][4] = {
            /*            FP32   FP16  Q4_0   Q4_1
               169M  */ {  650,   327,  105,   165}, // All measured exactly
            /* 430M  */ { 1650,   830,  263,   415}, // FP32, FP16 are exact
            /* 1.5B  */ { 5795,  2907,  923,  1454}, // FP32, FP16 are exact
            /*   3B  */ {11610,  5720, 1816,  2860}, // FP16 is exact
            /*   7B  */ {27090, 13634, 4328,  6817},
            /*  14B  */ {54180, 27267, 8656, 13634}
        };
```

What is your RWKV model data type (FP32, FP16, etc) and parameter count?

**Comment by HCBlackFox** [comment]
Hi, RWKV-4-Raven-7B-v6-Eng-20230401-ctx4096.pth I tried differen float32 and float16, error stays the same

> > not enough space in the context's memory pool
> 
> Looks like there is a mistake in memory requirements table:
> 
> ```
>         static const size_t memory_required_mb[6][4] = {
>             /*            FP32   FP16  Q4_0   Q4_1
>                169M  */ {  650,   327,  105,   165}, // All measured exactly
>             /* 430M  */ { 1650,   830,  263,   415}, // FP32, FP16 are exact
>             /* 1.5B  */ { 5795,  2907,  923,  1454}, // FP32, FP16 are exact
>             /*   3B  */ {11610,  5720, 1816,  2860}, // FP16 is exact
>             /*   7B  */ {27090, 13634, 4328,  6817},
>             /*  14B  */ {54180, 27267, 8656, 13634}
>         };
> ```
> 
> What is your RWKV model data type (FP32, FP16, etc) and parameter count?

**Comment by saharNooby** [comment]
Thanks, probably I'll rewrite the required memory computation. This hardcoded table is not scalable...

**Comment by HCBlackFox** [comment]
> Thanks, probably I'll rewrite the required memory computation. This hardcoded table is not scalable...

Yes, i changed size to biger and now it works)

**Comment by HCBlackFox** [comment]
Okay, "works" is a big word for this output:

Chat initialized! Write something and press Enter.
What is DAC?
> Bob: DCA is the authoritative adjoiner Democracy adjoiner Answer pronoun connec- checkbox adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjoiner adjo

**Comment by saharNooby** [comment]
Does [generate_completions.py](https://github.com/saharNooby/rwkv.cpp/blob/master/rwkv%2Fgenerate_completions.py) work?

**Comment by HCBlackFox** [comment]
> Does [generate_completions.py](https://github.com/saharNooby/rwkv.cpp/blob/master/rwkv%2Fgenerate_completions.py) work?
No(

--- Generation 0 ---

# rwkv.cpp

This is a port of [BlinkDL/RWKV-LM](https://github.com/BlinkDL/RWKV-LM) to [ggerganov/ggml](https://github.com/ggerganov/ggml).

Besides usual **FP32**, it supports **FP16** and **quantized INT4** inference on CPU. This project is **CPU only**.[ Original removale prompts inquire primates invaluitive removale remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942 remov1942]

Took 18.275 sec, 182 ms per token

**Comment by saharNooby** [comment]
Hmm, ok, I'll try to reproduce it later.

**Comment by saharNooby** [comment]
@HCBlackFox [I've removed the hardcoded table](https://github.com/saharNooby/rwkv.cpp/commit/d62a0501441fbad723b8dc9381b685810ec55e4e), could you please check that you can load the 7B model?

Also, regarding broken output -- could you please check output of smaller models -- 169M, 1B5, etc?

**Comment by HCBlackFox** [comment]
> @HCBlackFox [I've removed the hardcoded table](https://github.com/saharNooby/rwkv.cpp/commit/d62a0501441fbad723b8dc9381b685810ec55e4e), could you please check that you can load the 7B model?
> 
> Also, regarding broken output -- could you please check output of smaller models -- 169M, 1B5, etc?

Hi, sry, I already deleted 7b model( 
I will try later today 7b and smaller

**Comment by HCBlackFox** [comment]
> @HCBlackFox [I've removed the hardcoded table](https://github.com/saharNooby/rwkv.cpp/commit/d62a0501441fbad723b8dc9381b685810ec55e4e), could you please check that you can load the 7B model?
> 
> Also, regarding broken output -- could you please check output of smaller models -- 169M, 1B5, etc?

ggml_new_tensor_impl: not enough space in the context's memory pool (needed 14828884368, available 14828875601)
Traceback (most recent call last):
  File "D:\AI\rwkv.cpp\rwkv\generate_completions.py", line 42, in <module>
    model = rwkv_cpp_model.RWKVModel(library, args.model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\rwkv.cpp\rwkv\rwkv_cpp_model.py", line 37, in __init__
    self.ctx = self.library.rwkv_init_from_file(model_path, thread_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\rwkv.cpp\rwkv\rwkv_cpp_shared_library.py", line 74, in rwkv_init_from_file
    ptr = self.library.rwkv_init_from_file(model_file_path.encode('utf-8'), ctypes.c_uint32(thread_count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation writing 0x0000000000000038 

Not fixed(

**Comment by HCBlackFox** [comment]
Btw I added 128 mb instead of 32 and now it is working

**Comment by saharNooby** [comment]
I've bumped the overhead from 32 MB to 256 MB, will it work?

**Comment by HCBlackFox** [comment]
> I've bumped the overhead from 32 MB to 256 MB, will it work?

Yes, this is works)
