### ISSUE TITLE
Inference binary

### ISSUE THREAD

**Issue by drdaffey** [saharNooby/rwkv.cpp#42]
Very nice work! Any chance we can get a binary to do inference with, similar to llama.cpp, that is to say, without having to use Python? Thanks.

**Comment by saharNooby** [comment]
Hi! I have no plans of creating no-Python binary. But this project has C interface `rwkv.h` which can be called from C/C++.

For the tokenizer, [rwkv-cpp-cuda](https://github.com/harrisonvanderbyl/rwkv-cpp-cuda) has tokenizer implementation for RWKV in plain C++. I think it's possible to write a simple C/C++ app combining `rwkv.h` and this tokenizer, to get no-Python inference app.
