### ISSUE TITLE
AssertionError: xxxxxxxxx.bin is not a file

### ISSUE THREAD

**Issue by s567901** [saharNooby/rwkv.cpp#48]
![image](https://user-images.githubusercontent.com/53960657/235443671-fd992757-fe29-433b-90e8-7f9d00097bae.png)
Do you know how to fix it?

**Comment by saharNooby** [comment]
Most probably, the specified model file does not exist. Please double-check the path to it.

**Comment by PJ-568** [comment]
朋友，我和你遇到了相同的问题，但是我使用`管理员权限`的终端运行之后就好了！

* * *

My friend, I had the same problem as you, but I have fixed it by running the terminal with administrator privileges.
