### ISSUE TITLE
Library Fails to Build

### ISSUE THREAD

**Issue by wereretot** [saharNooby/rwkv.cpp#54]
cmake .                                                                                                                                                                                    ✔ 
cmake --build . --config Release
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
CMake Error at CMakeLists.txt:215 (add_subdirectory):
  The source directory

    /home/rexommendation/Downloads/rwkv.cpp-master-a3178b2/ggml

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:218 (set_target_properties):
  set_target_properties Can not find target to add properties to: ggml

-- Configuring incomplete, errors occurred!
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.

**Comment by saharNooby** [comment]
Hi! This duplicates https://github.com/saharNooby/rwkv.cpp/issues/29, solution is there.

If you insist on downloading zip file instead of cloning using `git`, you can download zip for `ggml` library and unpack it into `ggml` directory.
