### ISSUE TITLE
How can i build android rwkv.cpp?

### ISSUE THREAD

**Issue by xiaol** [saharNooby/rwkv.cpp#57]
Thank you for this promising work, 

like this one
https://github.com/ggerganov/llama.cpp#android

---------------
I have compiled with linux instructions ,and everything seems ok, but when i run python file, this error occured:

![Screenshot_2023-05-13-20-19-08-553_com termux](https://github.com/saharNooby/rwkv.cpp/assets/1669515/7338a687-b9ce-4ed8-86ea-362905d9517a)

**Comment by saharNooby** [comment]
The script can not find compiled library file. Look for newly created `.so` files in the repository directory, then specify path to the file explicitly [at this line](https://github.com/saharNooby/rwkv.cpp/blob/a3178b20ea0a1600f4d5d9dc06f67800d8bbb62a/rwkv/chat_with_bot.py#L58).

You can also try asking for help in `rwkv-cpp` channel in [RWKV Discord](https://discord.gg/bDSBUMeFpc), I saw people there running rwkv.cpp on Android.

**Comment by xiaol** [comment]
![Screenshot_2023-05-13-20-53-55-830_com.termux.jpg](https://github.com/saharNooby/rwkv.cpp/assets/1669515/a5c521cc-6f87-4273-b665-4a79218edf5d)

.so is there,that's odd.

yes,i find that guy who make it work in discord, i'll add more info here,he has a different approach.
