### ISSUE TITLE
Slow Inference

### ISSUE THREAD

**Issue by TheFaheem** [saharNooby/rwkv.cpp#67]
I'm Running RWKV -14B on 12 gigs of System RAM. This is What My Infrence Speed is ```Took 231.591 sec, 2315 ms per token``` 

is there anything i can do to decrease the inference speed?

**Comment by york-yu-ctw** [comment]
There is lot of ways to decrease the inference speed. 
But if you would like to increase it, you'd better to try
1.  turn on the OpenBlas
2. using gpu after https://github.com/saharNooby/rwkv.cpp/pull/65 been finished and merged
3. quantize the model to Q4_1 or Q4_0

**Comment by TheFaheem** [comment]
Will Try after getting merged...

**Comment by saharNooby** [comment]
@TheFaheem In addition to comment by @york-yu-ctw, I will also note that 2.3 sec per token is not outrageous for 14B on CPU. Alhtough it is on the high end -- for 14B, I would really expect something like 700 ms to 1.5 sec per token.

Additionally, you can also check that your system is not swapping (you have enough RAM for the model and all running processes) -- this KILLS performance.
