### ISSUE TITLE
question about the quantization

### ISSUE THREAD

**Issue by irasin** [saharNooby/rwkv.cpp#81]
How to generate the quantized INT4, INT5 and INT8 model?

Do you use GPTQ/RPTQ or normal per-tensor/per-channel PTQ? For quantized int8 model? Do you use int8 @ int8 -> int32 cublas?

**Comment by saharNooby** [comment]
1. How to quantize: [follow README.md](https://github.com/saharNooby/rwkv.cpp#3-get-an-rwkv-model).

2. "Do you use GPTQ/RPTQ": no; maybe they are experimenting with it in upstream `ggml`, but currently tensors are just split into fixed-size blocks of size 32 and then quantized block-wise.

3. "Do you use int8 @ int8 -> int32 cublas": don't know... You may check out [`ggml` CUDA code](https://github.com/ggerganov/ggml/blob/master/src/ggml-cuda.cu).
