### ISSUE TITLE
Compilation issue on Mac

### ISSUE THREAD

**Issue by mudler** [saharNooby/rwkv.cpp#82]
Hi :wave: 

First of all, amazing project :)

Let me clarify, I don't have a Mac to double test this - and our CI doesn't seems to catch this bug. I'm the author of LocalAI, and people are reporting since the last rwkv.cpp release that compilation broke with Mac https://github.com/go-skynet/LocalAI/issues/411 , any chance you can reproduce this locally?

Thanks!

**Comment by LoganDark** [comment]
Yes, the issue is the new stat stuff. My PR fixes this https://github.com/saharNooby/rwkv.cpp/blob/a8ebb07d2501dcb6fd544177022421660537030f/rwkv.cpp#L20-L36 but until @saharNooby is online to merge, you can try to apply that as a solution.
